"""ud uniqueconstraintlast

Revision ID: 0b94f9cf545b
Revises: 2f47bcfe3258
Create Date: 2023-05-17 13:05:21.893322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b94f9cf545b'
down_revision = '2f47bcfe3258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('city_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('city_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
