"""add location

Revision ID: 1ab46c74938d
Revises: 447ffbadd712
Create Date: 2023-05-16 11:07:07.919039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab46c74938d'
down_revision = '447ffbadd712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
