"""add location

Revision ID: 447ffbadd712
Revises: 823328c1aae8
Create Date: 2023-05-16 11:06:31.348612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447ffbadd712'
down_revision = '823328c1aae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('date_visited', sa.DateTime(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_locations_city_id_cities')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
