"""add location deets

Revision ID: 4cefc8b79e71
Revises: 7b55bb4d5cd5
Create Date: 2023-05-16 12:50:25.397006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cefc8b79e71'
down_revision = '7b55bb4d5cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###
