"""ud validator

Revision ID: 52aa5c36bb11
Revises: 9e69a47f398f
Create Date: 2023-05-24 00:39:06.738288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52aa5c36bb11'
down_revision = '9e69a47f398f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index('user_username_index', [sa.text('lower(country)'), sa.text('lower(city_name)'), 'user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('user_username_index')

    # ### end Alembic commands ###
