"""link location notes

Revision ID: 8227ddf9d286
Revises: cd7f670eb8b2
Create Date: 2023-05-16 16:54:51.839750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8227ddf9d286'
down_revision = 'cd7f670eb8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locationNotes', schema=None) as batch_op:
        batch_op.drop_column('note_type')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('locationNotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_type', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
