"""add user-city relationhips

Revision ID: 823328c1aae8
Revises: d8e478ea0f7d
Create Date: 2023-05-16 10:55:39.994463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823328c1aae8'
down_revision = 'd8e478ea0f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
