"""ud validator

Revision ID: 9e69a47f398f
Revises: dfb850c80255
Create Date: 2023-05-24 00:37:36.882262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e69a47f398f'
down_revision = 'dfb850c80255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_country', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_city_country', ['city_name', 'country', 'user_id'])

    # ### end Alembic commands ###
