"""ud uniqueconstraint

Revision ID: bf6199f60c73
Revises: d61ef9a5c7e7
Create Date: 2023-05-17 12:20:46.956664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6199f60c73'
down_revision = 'd61ef9a5c7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_city_country', ['city_name', 'country'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_country', type_='unique')

    # ### end Alembic commands ###
