"""add locaiton notes table

Revision ID: cd7f670eb8b2
Revises: d4604ae66568
Create Date: 2023-05-16 16:46:18.292300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7f670eb8b2'
down_revision = 'd4604ae66568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locationNotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_body', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_locationNotes_location_id_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locationNotes')
    # ### end Alembic commands ###
