"""add city notes table

Revision ID: d25d465bc7d0
Revises: 4cefc8b79e71
Create Date: 2023-05-16 13:01:39.940213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25d465bc7d0'
down_revision = '4cefc8b79e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cityNotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_body', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_cityNotes_city_id_cities')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cityNotes')
    # ### end Alembic commands ###
