"""ud uniqueconstraint

Revision ID: de9bdfd20c2a
Revises: bf6199f60c73
Create Date: 2023-05-17 12:22:44.344851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9bdfd20c2a'
down_revision = 'bf6199f60c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_country', type_='unique')
        batch_op.create_unique_constraint('unique_city_country', ['city_name', 'country', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_city_country', type_='unique')
        batch_op.create_unique_constraint('unique_city_country', ['city_name', 'country'])

    # ### end Alembic commands ###
