"""ud validator

Revision ID: f43fe5459faa
Revises: 52aa5c36bb11
Create Date: 2023-05-24 01:00:24.357371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43fe5459faa'
down_revision = '52aa5c36bb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('user_username_index')
        batch_op.create_index('user_city_country_index', [sa.text('lower(country)'), sa.text('lower(city_name)'), 'user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('user_city_country_index')
        batch_op.create_index('user_username_index', [sa.text('lower(country::text)'), sa.text('lower(city_name::text)'), 'user_id'], unique=False)

    # ### end Alembic commands ###
